### ISSUE TITLE
New Project

### ISSUE THREAD

**Issue by scxryshop** [cmpolis/convertSTL#6]
Hello, I am a Web Developer and I am trying to build my own 3D-print Website. I think a new project has to raise. Therefor to store stl files in the Web and read them. Also a function that alculates the price. Eventually turning it into cura but online.

**Comment by cmpolis** [comment]
hey - thanks for using this project! I don't see the question here, so I am closing, but if you have any specific questions or suggestions for this utility, please feel free to raise a new issue.
